In [1]:
import pandas as pd

df = pd.read_csv('C:/Users/pkuma/OneDrive/Desktop/Coding practice/Indian-Flights-Price-Analysis/data/Air-Clean.csv')
df.head()

,airline,flightNumber,origin,destination,daysOfWeek,scheduledDepartureTime,scheduledArrivalTime,timezone,validFrom,validTo,lastUpdated
0,GoAir,572,Goa,Hyderabad,"Thursday,Friday,Saturday",17:25,18:40,2021-03-27,2020-10-25,2021-03-27,2025-07-16
1,GoAir,301,Goa,Delhi,Saturday,12:00,14:45,2022-10-23,2022-03-27,2022-10-23,2025-07-16
2,GoAir,733,Goa,Nagpur,Saturday,12:10,13:40,2020-10-18,2020-03-29,2020-10-18,2025-07-16
3,GoAir,667,Goa,Lucknow,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",06:10,09:10,2019-10-26,2019-05-01,2019-10-26,2025-07-16
4,GoAir,247,Goa,Mumbai,Saturday,11:00,12:30,2022-03-20,2021-10-31,2022-03-20,2025-07-16

In [2]:
df_price = pd.read_csv('C:/Users/pkuma/OneDrive/Desktop/Coding practice/Indian-Flights-Price-Analysis/data/goibibo_flights_data.csv')
df_price.info()
df_price.columns.tolist()
df_price.head()

<class 'pandas.DataFrame'>
RangeIndex: 300261 entries, 0 to 300260
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   flight date  300261 non-null  str
 1   airline      300261 non-null  str
 2   flight_num   300261 non-null  str
 3   class        300261 non-null  str
 4   from         300261 non-null  str
 5   dep_time     300261 non-null  str
 6   to           300261 non-null  str
 7   arr_time     300261 non-null  str
 8   duration     300261 non-null  str
 9   price        300261 non-null  str
 10  stops        300261 non-null  str
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
dtypes: float64(2), str(11)
memory usage: 29.8 MB

,flight date,airline,flight_num,class,from,dep_time,to,arr_time,duration,price,stops,Unnamed: 11,Unnamed: 12
0,26-06-2023,SpiceJet,SG-8709,economy,Delhi,18:55,Mumbai,21:05,02h 10m,"6,013",non-stop,NaN,NaN
1,26-06-2023,SpiceJet,SG-8157,economy,Delhi,06:20,Mumbai,08:40,02h 20m,"6,013",non-stop,NaN,NaN
2,26-06-2023,AirAsia,I5-764,economy,Delhi,04:25,Mumbai,06:35,02h 10m,"6,016",non-stop,NaN,NaN
3,26-06-2023,Vistara,UK-995,economy,Delhi,10:20,Mumbai,12:35,02h 15m,"6,015",non-stop,NaN,NaN
4,26-06-2023,Vistara,UK-963,economy,Delhi,08:50,Mumbai,11:10,02h 20m,"6,015",non-stop,NaN,NaN

In [4]:
df_price['flight date'] = pd.to_datetime(df_price['flight date'], dayfirst=True)
print(df_price['flight date'].min())
print(df_price['flight date'].max())

2023-06-26 00:00:00
2023-08-13 00:00:00